Repository FRONTENDBOOTCAMP-11th/febc11-vanilla-team1, pull requests merged in 2024-10, with the labels that each got.

#14 test: PR test
  counter.js
  main.js
Labels: documentation

#15 chore: Refactor pull request template
  .github/pull_request_template.md
Labels: documentation

#21 [FEAT] 상품 리스트 퍼블리싱
  api/dbinit/brunchStory/data.js
  api/dbinit/brunchStory/uploadFiles/exam1.png
  api/dbinit/brunchStory/uploadFiles/exam2.png
  api/dbinit/brunchStory/uploadFiles/keyword.png
  api/dbinit/brunchStory/uploadFiles/no_shooni.jpg
  api/dbinit/brunchStory/uploadFiles/user-apeach.webp
  api/dbinit/brunchStory/uploadFiles/user-jayg.webp
  api/dbinit/brunchStory/uploadFiles/user-muzi.webp
  api/dbinit/brunchStory/uploadFiles/user-neo.webp
  api/dbinit/getDB.js
  api/dbinit/init.js
  api/dbinit/nike/data.js
  api/dbinit/nike/uploadFiles/exam1.png
  api/dbinit/nike/uploadFiles/exam2.png
  api/dbinit/nike/uploadFiles/keyword.png
  api/dbinit/nike/uploadFiles/no_shooni.jpg
  api/dbinit/nike/uploadFiles/user-apeach.webp
  api/dbinit/nike/uploadFiles/user-jayg.webp
  api/dbinit/nike/uploadFiles/user-muzi.webp
  api/dbinit/nike/uploadFiles/user-neo.webp
  api/dbinit/package-lock.json
  api/dbinit/package.json
  api/nike/bruno.json
  api/nike/collection.bru
  api/nike/environments/nike-dev.bru
  api/nike/게시물/게시글 목록 조회.bru
  api/nike/회원 관리/로그인.bru
  public/assets/icons/buttons/l-fill-x.svg
  src/components/footer/footer.css
  src/components/footer/footer.html
  src/pages/board/list.css
  src/pages/board/list.html
  src/pages/board/list.js
  src/pages/board/uiHandler.js
  vite.config.js
Labels: enhancement, P1

#22 Feature/7 auth/doyoung #7
  .gitignore
  package-lock.json
  public/assets/icons/buttons/blank-social.svg
  public/assets/icons/buttons/kakao.svg
  public/assets/icons/buttons/question.svg
  public/assets/icons/buttons/social.svg
  src/pages/auth/auth.css
  src/pages/auth/check.html
  src/pages/auth/check.js
  src/pages/auth/complete.html
  src/pages/auth/login.html
  src/pages/auth/login.js
  src/pages/auth/pw.html
  src/pages/auth/pw.js
  src/pages/auth/signup.html
  src/pages/auth/sjgnup.js
  src/pages/auth/social.html
  src/pages/auth/social.js
  style.css
Labels: P1

#29 feat. cart 퍼블리싱 #5
  public/assets/icons/button36px/delete.svg
  src/cart/cart.css
  src/cart/cart.html
  src/cart/cart.js
Labels: enhancement, P1

#34 [FIX] prettier 적용, 파일 위치 pages 폴더 안으로 변경
  src/pages/cart/cart.css
  src/pages/cart/cart.html
  src/pages/cart/cart.js
Labels: bug, P2

#32 [FIX] 각 마크업 줄 간격 (Tab) 2칸 이상으로 편집
  src/pages/product-details/product-details.html
Labels: bug, P2

#38 Feature/37 auth/doyoung
  .gitignore
  src/pages/auth/auth.css
  src/pages/auth/check.html
  src/pages/auth/check.js
  src/pages/auth/complete.html
  src/pages/auth/login.html
  src/pages/auth/login.js
  src/pages/auth/pw.html
  src/pages/auth/pw.js
  src/pages/auth/signup.html
  src/pages/auth/sjgnup.js
  src/pages/auth/social.html
  src/pages/auth/social.js
Labels: P2

#41 fix: KEY 위치 변경 및 소셜 로그인 로직 수정 #40
  .gitignore
  src/pages/auth/login.html
  src/pages/auth/login.js
Labels: bug

#44 Feature/42, 43 auth/doyoung
  src/pages/auth/check.html
  src/pages/auth/check.js
  src/pages/auth/login.html
  src/pages/auth/login.js
  src/pages/auth/pw.js
  src/pages/auth/signup.html
  src/pages/auth/sjgnup.js
  src/pages/auth/social.html
  src/pages/auth/social.js
Labels: bug, enhancement

#46 Feature/create components/reno
  src/components/footer/footer.css
  src/components/footer/footer.html
  src/components/footer/footer.js
  src/components/header/header.css
  src/components/header/header.html
  src/components/header/header.js
  src/pages/MainHome/home.html
  src/pages/board/list.css
  src/pages/board/list.html
Labels: enhancement, P1

#47 fix: 절대 경로 수정 #43
  src/pages/auth/check.js
  src/pages/auth/login.js
  src/pages/auth/pw.js
  src/pages/auth/sjgnup.js
Labels: bug

#54 fix: 로그인, 비밀번호 입력페이지 병합 및 데이터 전송 에러 해결 #50, #53
  src/pages/auth/auth.css
  src/pages/auth/check.js
  src/pages/auth/complete.html
  src/pages/auth/login.html
  src/pages/auth/login.js
  src/pages/auth/pw.html
  src/pages/auth/pw.js
  src/pages/auth/sjgnup.js
  vite.config.js
Labels: bug, P1

#49 [FEAT]map/list 탭전환 기능 추가
  src/pages/FindStore/FindStore.css
  src/pages/FindStore/FindStore.html
  src/pages/FindStore/FindStores.js
Labels: P2

#64 [FEAT] 파일 및 폴더 경로 수정
  index.html
  src/components/header/header.html
  src/pages/FindStore/FindStore.html
  src/pages/product/cart/index.html
  src/pages/product/cart/index.js
  src/pages/product/cart/styles.css
  src/pages/product/detail/index.html
  src/pages/product/detail/main.js
  src/pages/product/detail/styles.css
  src/pages/product/detail/swiper.js
  src/pages/product/detail/swiper.min.css
  src/pages/product/detail/swiper.min.js
  src/pages/stores/index.css
  src/pages/stores/index.html
  src/pages/stores/index.js
Labels: enhancement, P1

#60 [FEAT] 로그인 시 헤더 부분 데이터 변경
  src/components/header/header.css
  src/components/header/header.html
  src/components/header/header.js
  src/pages/auth/auth.css
  src/pages/auth/login.js
  src/pages/auth/sjgnup.js
  src/pages/product/list/index.html
Labels: enhancement, P1

#66 feat: 헤더 로그인, 로그아웃 버튼 활성, 모바일 로그인, 로그아웃 기능 추가, 헤더 및 모바일 CSS 변경, 패스워드 …
  public/assets/icons/button/Button-login.svg
  public/assets/icons/button/Button-logout.svg
  public/assets/icons/button/Button-signup.svg
  src/components/header/header.css
  src/components/header/header.html
  src/components/header/header.js
  src/pages/auth/login.js
Labels: bug, enhancement

#69 fix: 반응형 네비바 아이콘 안보임, 반응형 로그인, 회원가입 버튼 위치 변경, 로그인 선언 위치 수정
  src/components/header/header.css
  src/components/header/header.html
  src/pages/auth/login.js
Labels: bug

#70 Feature/67 category refactoring/reno
  .gitignore
  api/dbinit-sample/nike/data.js
  src/components/header/header.css
  src/components/header/header.html
  src/components/header/header.js
  src/pages/auth/login.js
  src/pages/product/list/category.js
  src/pages/product/list/index.html
  src/pages/product/list/index.js
  src/pages/product/list/styles.css
Labels: enhancement, P1

#81 Feature/80 view cart/suhyun
  src/pages/product/cart/index.html
  src/pages/product/cart/index.js
  src/pages/product/cart/styles.css
Labels: enhancement, P1

#89 [Refactor] 상품 리스트 모바일 필터 리펙토링
  src/components/header/header.html
  src/pages/product/list/index.html
  src/pages/product/list/index.js
  src/pages/product/list/styles.css
  src/pages/product/list/uiHandler.js
Labels: enhancement, P2

#86 [FIX] 재사용성 필요한 코드 함수화, api 함수 적용, CSS 변경 #82
  src/pages/auth/check.html
  src/pages/auth/login.html
  src/pages/auth/login.js
  src/pages/auth/signup.html
  src/pages/auth/sjgnup.js
Labels: documentation

#93 [FEAT]: 상품 리스트 무한 스크롤 기능 추가
  api/dbinit-sample/nike/data.js
  api/dbinit/nike/data.js
  src/pages/product/list/index.js
Labels: enhancement, P1

#92 [FEAT] 로그인 전 상황에서 장바구니 페이지 접속 가능하도록 수정
  package-lock.json
  src/components/header/header.html
  src/pages/product/cart/index.js
Labels: enhancement, P1

#95 [FEAT]: Update image URLs to use the correct path
  src/pages/product/cart/index.js
  src/pages/product/cart/styles.css
Labels: enhancement, P2

#97 Styles/96 global styles/Reno
  global.css
  index.html
  src/components/header/header.html
  src/components/header/header.js
  src/pages/auth/check.html
  src/pages/auth/login.html
  src/pages/auth/login.js
  src/pages/auth/signup.html
  src/pages/auth/sjgnup.js
  src/pages/product/cart/index.html
  src/pages/product/cart/index.js
  src/pages/product/detail/index.html
  src/pages/product/list/index.html
  src/pages/product/list/styles.css
Labels: P2

#99 style: 반응형 CSS 변경 및 글로벌 CSS 중복 제거 #98
  src/pages/auth/auth.css
Labels: bug

#100 [FEAT]: 정렬 옵션 UI 개선 및 정렬 로직 추가
  src/pages/product/list/index.html
  src/pages/product/list/index.js
  src/pages/product/list/styles.css
Labels: enhancement, P2

#102 fix: 상품 조회 시 undefined 오류 수정 / Fix: Update CSS styles
  src/pages/product/cart/index.html
  src/pages/product/cart/index.js
  src/pages/product/cart/styles.css
Labels: bug, enhancement, P2

#105 fix: url 변경
  src/pages/auth/login.js
  src/pages/auth/sjgnup.js
Labels: documentation

#106 이미지 깨짐 현상 수정
  src/pages/product/cart/index.js
Labels: bug, P2
