Repository FRONTENDBOOTCAMP-11th/febc11-vanilla-team1, pull requests merged in 2024-11, with the labels that each got.

#108 [FEAT] 사이드바 블러 추가, 헤더 CSS, 체크 약관 페이지 유효성 추가 #107
  src/components/header/header.css
  src/components/header/header.html
  src/components/header/header.js
  src/pages/auth/auth.css
  src/pages/auth/check.html
  src/pages/auth/check.js
  src/pages/auth/login.js
  src/pages/auth/sjgnup.js
Labels: enhancement

#109 <FEAT> 퍼블리싱, api 상품명, 이미지 랜더링 적용
  api/openmarket/01.회원/01 회원가입,로그인/회원 가입.bru
  api/openmarket/02.일반 회원/folder.bru
  api/openmarket/03.판매 회원/01.상품 관리/내 상품 목록 조회.bru
  api/openmarket/03.판매 회원/01.상품 관리/내 상품 상세 조회.bru
  api/openmarket/collection.bru
  api/vanilla-brunch/bruno.json
  api/vanilla-brunch/collection.bru
  api/vanilla-brunch/environments/sample.bru
  api/vanilla-brunch/제품 상세.bru
  public/assets/icons/etc/high-reputation.svg
  public/assets/icons/etc/♡.svg
  src/pages/product/detail/index.html
  src/pages/product/detail/index.js
  src/pages/product/detail/main.js
  src/pages/product/detail/styles.css
Labels: enhancement, P1

#110 <FEAT> 지도 api추가, wish 삭제기능 추가
  public/assets/images/wishdelbtn.png
  public/assets/images/wishdelete.png
  public/assets/images/wishmodify.png
  src/pages/product/wishlist/index .html
  src/pages/product/wishlist/index.js
  src/pages/product/wishlist/styles.css
  src/pages/stores/index.css
  src/pages/stores/index.html
  src/pages/stores/index.js
Labels: enhancement, P1

#112 wishlist 예시 주석처리
  src/pages/product/cart/index.js
Labels: P3
